config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'

get 'signup' => 'users#new', :as => :signup
get 'login' => 'user_sessions#new', :as => :login
post 'login' => 'user_sessions#create'
delete 'logout' => 'user_sessions#destroy', :as => :logout

get 'preload' => 'reservations#preload'
get 'check_conflict' => 'reservations#check_conflict'
get 'your_trips' => 'reservations#your_trips'
get 'your_reservations' => 'reservations#your_reservations'
get 'search' => 'static_pages#search'
get "oauth/callback" => "oauths#callback"
get "oauth/vkontakte" => "oauths#vkontakte"
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
post "oauth/callback" => "oauths#callback"

resources :user_sessions, only: [:new, :create, :destroy]
resources :users
resources :password_resets, only: [:new, :create, :edit, :update]
resources :account_activations, only: [:edit]
resources :photos

resources :rooms do
  resources :reservations, only: [:create]
  resources :reviews, only: [:create, :destroy]
end

resources :conversations, only: [:create, :index] do
  resources :messages, only: [:create, :index] do
    collection { get :events }
  end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :conversations
  has_many :messages, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :authentications, :dependent => :destroy

  accepts_nested_attributes_for :authentications
  attr_accessor :activation_token

  validates :password, length: { minimum: 4 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 200},
                    format: { with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :first_name, presence: true, length: {maximum: 50}
  validates :last_name, presence: true, length: {maximum: 50}

  before_create :create_activation_digest


  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def check_activation_token(token)
    digest = self.activation_digest
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  private

    def create_activation_digest
      self.activation_token = SecureRandom.urlsafe_base64
      self.activation_digest = User.digest(activation_token)
    end

    def self.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ?
      BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]
  before_action :has_access?, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @rooms = @user.rooms
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html {
          UserMailer.account_activation(@user).deliver_now
          flash[:info] = "Please check your email to activate your account."
          redirect_to root_path
        }
        format.json { redirect_to root_path, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, flash: {success: 'User was successfully updated.'} }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, flash: {success: 'User was successfully destroyed.'} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def has_access?
      redirect_to(root_path, flash: {danger: "You haven't permission"}) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= render 'shared/form_error_messages', object: form.object %>

<div class="form-group">
  <%= form.label :first_name %>
  <%= form.text_field :first_name, class:"form-control" %>
</div>

<div class="form-group">
  <%= form.label :last_name %>
  <%= form.text_field :last_name, class:"form-control" %>
</div>

<div class="form-group">
  <%= form.label :email %>
  <%= form.text_field :email, class:"form-control" %>
</div>

<div class="form-group">
  <%= form.label :password %><br />
  <%= form.password_field :password, class:"form-control" %>
</div>

<div class="form-group">
   <%= form.label :password_confirmation %><br />
   <%= form.password_field :password_confirmation, class:"form-control" %>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>

<div class="row">
  <aside class="col-sm-12 col-md-3">
      <ul class="sidebar">
        <li class="sidebar-item">
          <%= link_to "Edit Profile", edit_user_path(@user), class: "sidebar-link sidebar-active" %>
        </li>
      </ul>
    <%= link_to 'Show', @user , class: "btn btn-default w-100"%>
  </aside>
  <div class="col-sm-12 my-sm-3 my-md-0 col-md-9">
    <div class="card">
      <div class="card-header">
        Required Information
      </div>

      <div class="card-body">
        <div class="row">
          <div class="col-md-6 offset-md-3">
            <%= form_with(model: @user, local: true) do |form| %>
              <%= render 'fields', form: form %>

              <%= form.submit "Save changes", class: "btn btn-fox w-100" %>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<h1>Users</h1>

<table class="table">
  <thead>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>

<div class="row">
  <div class="col-md-8 offset-md-2 col-lg-8 offset-lg-2">
    <div class="card">
      <div class="card-header">Registration</div>
      <div class="card-body">
        <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3">
          <%= form_with(model: @user, local: true) do |form| %>
            <%= render 'fields', form: form %>

            <%= form.submit "Create my account", class: "btn btn-fox w-100" %>
            <div class="text-center">
              <%= link_to auth_at_provider_path(:provider => :vk) do %>
                <i class="fab fa-vk fa-2x"></i>
              <% end %>
              |
              <%= link_to auth_at_provider_path(:provider => :facebook) do %>
                <i class="fab fa-facebook-square fa-2x"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.full_name) %>
<div class="row">
  <aside class="col-sm-12 col-md-3 user_profile">
    <section class="profile_photo">
      <%= image_tag gravatar_url(@user, size: 300), class: "center-block" %>
    </section>

    <section class="profile-btn-section">
      <% if current_user?(@user) %>
        <%= link_to "Edit Profile", edit_user_path(current_user), class: "btn btn-default" %>
        <%= link_to "Messages", conversations_path, class: "btn btn-fox" %>
      <% else %>
        <%= link_to "Send message", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :post, class: "btn btn-fox" %>
      <% end %>
    </section>

    <section class="card verification_panel">
      <div class="card-header">
        Verification
      </div>
      <div class="card-body">
        <ul>
          <li>
            <div class="row">
              <div class="col-9">Email address</div>
              <div class="col-3"><i class="far fa-check-circle"></i></div>
            </div>

          </li>
          <li>
            <div class="row">
              <div class="col-9">Phone</div>
              <div class="col-3"><i class="far fa-check-circle"></i></div>
            </div>
          </li>
        </ul>
      </div>
    </section>
  </aside>
  <div class="col-sm-12 my-sm-3 my-md-0 col-md-9">
    <h2>Hello, my name is <%= @user.full_name %> </h2>
    <p>on the site since <%= @user.created_at.strftime("%B %Y") %></p>

    <h4>Listings (<%= @rooms.count %>)</h4>

    <div class="row">
      <%= render @rooms %>
    </div>

    <br>
    <h4>Reviews</h4>

    <% @rooms.each do |room| %>
      <% unless room.reviews.blank? %>
        <% room.reviews.each do |review| %>
          <div class="review bordered-review">
            <div class="review-avatar">
              <%= image_tag gravatar_url(review.user, size: 60), class: "rounded-circle" %>
              <div><%= review.user.full_name %></div>
            </div>
            <div class="review-body">
              <div class="review-header">
                <span>
                  <%= link_to room.listing_name, room_path(room) %>
                </span>

                <span class="float-right review-date">
                  <%= review.created_at.strftime("%v").downcase %>
                </span>
                <div id="star_<%= review.id %>"></div>
              </div>

              <div class="review-content"><%= review.comment %></div>
            </div>
          </div>
          <script>
            $("#star_<%= review.id %>").raty({
              path: '/assets',
              readOnly: true,
              score: <%= review.star %>
            })
          </script>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>