config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'

get 'signup' => 'users#new', :as => :signup
get 'login' => 'user_sessions#new', :as => :login
post 'login' => 'user_sessions#create'
delete 'logout' => 'user_sessions#destroy', :as => :logout

get 'preload' => 'reservations#preload'
get 'check_conflict' => 'reservations#check_conflict'
get 'your_trips' => 'reservations#your_trips'
get 'your_reservations' => 'reservations#your_reservations'
get 'search' => 'static_pages#search'
get "oauth/callback" => "oauths#callback"
get "oauth/vkontakte" => "oauths#vkontakte"
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
post "oauth/callback" => "oauths#callback"

resources :user_sessions, only: [:new, :create, :destroy]
resources :users
resources :password_resets, only: [:new, :create, :edit, :update]
resources :account_activations, only: [:edit]
resources :photos

resources :rooms do
  resources :reservations, only: [:create]
  resources :reviews, only: [:create, :destroy]
end

resources :conversations, only: [:create, :index] do
  resources :messages, only: [:create, :index] do
    collection { get :events }
  end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :listing_name, presence: true, length: {maximum: 80}
  validates :summary, presence: true, length: {maximum: 1000}
  validates :address, presence: true

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  before_action :require_login, except: [:show]
  before_action :correct_room?, only: [:edit, :update, :destroy]

  def index
    @rooms = current_user.rooms
  end

  def show
    @photos = @room.photos

    @booked = Reservation.where("room_id = ? AND user_id = ?", @room.id, current_user.id).present? if current_user

    @reviews = @room.reviews.order("id DESC")
    @review = @reviews.find_by(user_id: current_user.id) if current_user
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end
      flash[:success] = "Successfully created..."
      redirect_to @room
    else
      render :new
    end
  end

  def edit
    @photos = @room.photos
  end

  def update
    if @room.update(room_params)
      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end
      flash[:success] = "Successfully updated..."
      redirect_to @room
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:home_type, :room_type, :accommodate,
                                  :bed_room, :bath_room, :listing_name,
                                  :summary, :address, :is_tv, :is_kitchen,
                                  :is_air, :is_internet, :is_heating, :price,
                                  :active)
  end

  def correct_room?
    redirect_to(root_path, flash: {danger: "You haven't permission"}) unless current_user.id == @room.user_id
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div class="card">
  <div class="card-header"><%= card_title %></div>
  <div class="card-body">
    <div class="col-sm-10 m-auto">
      <%= form_for @room, html: {multipart: true} do |f| %>

        <%= render 'shared/form_error_messages', object: f.object %>

        <div class="row">
          <div class="col-sm-4 select">
            <div class="form-group">
              <%= f.label :home_type %>
              <%= f.select :home_type, [  %w(Apartment Apartment),
                                          %w(House House),
                                          %w(Bed & Breakfast, Bed & Breakfast)
                                        ], {}, {  prompt: "Select...",
                                                  class: "form-control"} %>
            </div>
          </div>

          <div class="col-sm-4 select">
            <div class="form-group">
              <%= f.label :room_type %>
              <%= f.select :room_type, [  %w(Entire Entire),
                                          %w(Private Private),
                                          %w(Shared, Shared)
                                        ],  {}, { prompt: "Select...",
                                                  class: "form-control"} %>
            </div>
          </div>

          <div class="col-sm-4 select">
            <div class="form-group">
              <%= f.label :accommodate %>
              <%= f.select :accommodate, [  ["1", 1], ["2", 2], ["3", 3],
                                            ["4", 4], ["5", 5], ["6+", 6]
                                        ], {}, { prompt: "Select...",
                                              class: "form-control"} %>
            </div>
          </div>

        </div>

        <div class="row">
          <div class="col-sm-4 select">
            <div class="form-group">
              <%= f.label :bed_room, "Bedrooms" %>
              <%= f.select :bed_room, [  ["1", 1], ["2", 2], ["3", 3],
                                            ["4+", 4]], {},
                                            { prompt: "Select...",
                                              class: "form-control" } %>
            </div>
          </div>
          <div class="col-sm-4 select">
            <div class="form-group">
              <%= f.label :bath_room, "Bathrooms" %>
              <%= f.select :bath_room, [  ["1", 1], ["2", 2], ["3", 3],
                                            ["4+", 4]], {},
                                            { prompt: "Select...",
                                              class: "form-control" } %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <%= f.label :listing_name %>
              <%= f.text_field :listing_name,
                                        placeholder: "Be clear and descriptive",
                                        class:       "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <%= f.label :summary %>
              <%= f.text_area :summary, rows: 4, placeholder: "Tell about your house",
                                              class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-12">
            <div class="form-group">
              <%= f.label :address %>
              <%= f.text_field :address, placeholder: "What is your address?",
                                              class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group form-check">
              <%= f.label :is_tv, class: "form-check-label" do %>
                <%= f.check_box :is_tv, class: "form-check-input" %>
                <span>TV</span>
              <% end %>
            </div>

            <div class="form-group form-check">
              <%= f.label :is_kitchen, class: "form-check-label" do %>
                <%= f.check_box :is_kitchen, class: "form-check-input" %>
                <span>Kitchen</span>
              <% end %>
            </div>

            <div class="form-group form-check">
              <%= f.label :is_internet, class: "form-check-label" do %>
                <%= f.check_box :is_internet, class: "form-check-input" %>
                <span>Internet</span>
              <% end %>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group form-check">
              <%= f.label :is_heating, class: "form-check-label" do %>
                <%= f.check_box :is_heating, class: "form-check-input" %>
                <span>Heating</span>
              <% end %>
            </div>

            <div class="form-group form-check">
              <%= f.label :is_air, class: "form-check-label" do %>
                <%= f.check_box :is_air, class: "form-check-input" %>
                <span>Air Conditioning</span>
              <% end %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <%= f.label :price, "Nightly Price" %>
              <%= f.text_field :price, placeholder: "eg. 100$", class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <span class="btn btn-file btn-default">
                <i class="fas fa-cloud-upload-alt fa-lg"></i> Upload photos
                <%= file_field_tag "images[]", type: :file, multiple: true %>
              </span>

            </div>
          </div>
        </div>

        <div id="photos">
          <%= render 'photos/list' %>
        </div>

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group form-check">
              <%= f.label :active, class: "form-check-label" do %>
                <%= f.check_box :active, class: "form-check-input" %>
                <span>Active</span>
              <% end %>
            </div>
          </div>
        </div>

        <%= f.submit submit_name, class: "btn btn-fox" %>
      <% end %>
    </div>

  </div>
</div>

<script>
class PhotoPreview {
  constructor(options = {}) {
    this.container = options.container;
    this.input = options.input;
    this._handleFile(this.input);
    // this.files = [];
    // this._handleDestroyFile();
  }

  _createElem(elem, className = ""){
    let div = document.createElement(elem);
    div.className = className;
    return div;
  }

  _createCard(file){
    let colDiv = this._createElem("div", "col-sm-4");
    let cardDiv = this._createElem("div", "card photo-preview");
    let cardHeaderDiv = this._createElem("div", "card-header");
    let cardBodyDiv = this._createElem("div", "card-body");
    colDiv.appendChild(cardDiv);
    cardDiv.appendChild(cardHeaderDiv);
    cardDiv.appendChild(cardBodyDiv);
    // let i = this._createElem("i", "fas fa-times fa-lg float-right");
    // i.setAttribute('data-destroy-photo', '');
    // cardBodyDiv.appendChild(i);

    let img = this._createElem("img", "card-img-top");
    img.src = file.result;
    cardHeaderDiv.appendChild(img);

    return colDiv;
  }

  _handleFile(input){

    input.oninput = (event) => {
      let files = event.target.files;

      for (var i = 0; i < files.length; i++) {
        let file = files[i];

        if (!file.type.match("image.*")) {
          continue;
        };

        var reader = new FileReader();

        reader.onload = (event) => {
          let card = this._createCard(event.target);
          this.container.appendChild(card);
        };

        reader.onerror = function(event) {
          console.error(
            `The file ${event.target.name} can't be readed. Error code: ${event.target.error.code}`
          );
        };
        reader.readAsDataURL(file);
      }
    }
  }

  // _handleDestroyFile(){
  //   this.container.onclick = (event) => {
  //     if (!event.target.hasAttribute('data-destroy-photo')){
  //       return;
  //     }
  //     let colDiv = event.target.closest('.col-sm-4');
  //     colDiv.parentElement.removeChild(colDiv);
  //
  //   }
  // }
};

$(
  function preparePreview(){
    let input = document.querySelector('.btn-file input');
    let container = document.getElementById('photo-preview');
    if(!input || !container ){
      return false;
    }
    new PhotoPreview({container: container, input: input});
  }
)
</script>

app/views/rooms/_room.html.erb
<div class="col-lg-3 col-md-4 col-sm-6 col-6 photo-card">
  <div class="photo-container">
    <div class="photo-header">
      <% unless room.photos.blank? %>
        <%= image_tag room.photos.first.image.url(:medium) %>
      <% else %>
        <div class="no-img">No image</div>
      <% end %>
    </div>
    <div class="photo-body">
      <span class="photo-title">
        <%= link_to room.listing_name, room %>
      </span>
      <p class="lead"><%= room.price %>$ per night</p>
    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/destroy.html.erb
<h1>Rooms#destroy</h1>
<p>Find me in app/views/rooms/destroy.html.erb</p>

app/views/rooms/edit.html.erb
<% provide(:title, "Update your place") %>

<%= render 'form', {card_title: "Edit your place", submit_name: "Save changes"} %>

app/views/rooms/index.html.erb
<%= provide(:title, "Your rooms") %>
<div class="row">
  <div class="col-sm-3">
    <ul class="sidebar">
      <li class="sidebar-item">
        <%= link_to "Your Listing", rooms_path, class: "sidebar-link sidebar-active" %>
      </li>
      <li class="sidebar-item">
        <%= link_to "Your Reservaions",your_reservations_path, class: "sidebar-link" %>
      </li>
      <li class="sidebar-item">
        <%= link_to "Your trips", your_trips_path, class: "sidebar-link" %>
      </li>
    </ul>
  </div>
  <div class="col-sm-9">
    <div class="card">
      <div class="card-header">Listings</div>
      <div class="card-body">
        <% @rooms.each do |room| %>
          <div class="row">
            <div class="col-sm-2">
              <%= link_to room_path(room) do %>
                <%= image_tag room.photos[0].image.url(:thumb) unless room.photos.empty? %>
              <% end %>
            </div>
            <div class="col-sm-7">
              <h4><%= link_to room.listing_name, room_path(room), class:"item-link" %></h4>
            </div>
            <div class="col-sm-3">
              <%= link_to "Update", edit_room_path(room), class: "btn btn-fox" %>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<% provide(:title, "Create your beautiful place") %>

<%= render 'form', {card_title: "Create your beautiful place", submit_name: "Create"} %>

app/views/rooms/show.html.erb
<%= provide(:title, @room.listing_name) %>
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm-12 justify-content-center text-center">
        <%= image_tag @photos.first.image.url(), class: "img-fluid w-100" unless @photos.blank? %>
      </div>
    </div>

    <br>

    <div class="row my-3">
      <div class="col-sm-12 col-md-8">
        <div class="row">
          <div class="col-sm-12 col-md-3 text-center">
            <%= link_to user_path(@room.user) do %>
              <%= image_tag gravatar_url(@room.user, size:100), class: "rounded-circle img-fluid" %>
              <p class="h4 text-dark">
                <%= @room.user.full_name %>
              </p>
            <% end %>
          </div>

          <div class="col-sm-12 col-md-9 mb-sm-3 mb-md-0">
            <h4><%= @room.listing_name %></h4>
            <p><%= @room.address %></p>

            <div class="row text-center row-space-1">
              <div class="col-sm-3"><i class="fas fa-home fa-2x"></i></div>
              <div class="col-sm-3"><i class="fas fa-users fa-2x"></i></div>
              <div class="col-sm-3"><i class="fas fa-bed fa-2x"></i></div>
              <div class="col-sm-3"><i class="fas fa-ship fa-2x"></i></div>
            </div>

            <div class="row text-center">
              <div class="col-sm-3">
                <%= @room.home_type %>
              </div>
              <div class="col-sm-3">
                <%= pluralize(@room.accommodate, "Guest") %>
              </div>
              <div class="col-sm-3">
                <%= pluralize(@room.bed_room, "Bedroom") %>
              </div>
              <div class="col-sm-3">
                <%= pluralize(@room.bath_room, "Bathroom") %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-10 offset-sm-1 col-md-4 offset-md-0">
        <div class="room-price">
          <span class="text-left">$<%= @room.price %></span>
          <span class="text-right">Per Night</span>
        </div>
        <div>
          <% if logged_in? %>
            <%= render 'reservations/form' unless current_user?(@room.user)%>
          <% else %>
            <h5>Sign in to book this room.</h5>
          <% end %>
        </div>
      </div>
    </div>

    <hr>

    <!-- About this Listing -->
    <div class="row my-3">
      <div class="col-sm-12">
        <h2>About this Listing</h2>
        <p><%= @room.summary %></p>
      </div>
    </div>

    <hr>
    <br>
    <!-- Amentities -->
    <div class="row my-3">
      <div class="col-sm-2">
        <p>Amentities</p>
      </div>
      <div class="col-sm-10">
        <div class="row">
          <div class="col-sm-6">
            <ul class="amentities">
              <li class="<%= 'text-line-through' unless @room.is_tv %>">
                <span class="icon">
                  <i class="fas fa-tv fa-1x2"></i>
                </span>
                <span>TV</span>
              </li>
              <li class="<%= 'text-line-through' unless @room.is_kitchen %>">
                <span class="icon">
                  <i class="fas fa-utensils fa-1x2 mr-2"></i>
                </span>
                <span>Kitchen</span>
              </li>
              <li class="<%= 'text-line-through' unless @room.is_internet %>">
                <span class="icon"><i class="fas fa-wifi fa-1x2"></i></span>
                <span>Internet</span>
              </li>
            </ul>
          </div>
          <div class="col-sm-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' unless @room.is_heating %>"><i class='icon i-heating'></i>Heating</li>
              <li class="<%= 'text-line-through' unless @room.is_air %>"><i class="icon i-air-condition"></i>Air Conditioning</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <hr>
    <br>
    <!-- Carousel -->
    <div class="row my-3">
      <div class="col-md-10 offset-md-1 d-flex justify-content-center">
        <% unless @photos.blank? %>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <% @photos.each_with_index do |photo, i| %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>" class="<%= 'active' if i == 0 %>"></li>
            <% end %>
          </ol>
          <div class="carousel-inner">
            <% @photos.each do |photo| %>
              <div class="carousel-item <%= 'active' if photo.id == @photos.first.id %>">
                <%= image_tag photo.image.url(), class: "d-block w-100" %>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        <% else %>
          <% if current_user?(@room.user) %>
            <%= link_to "Add photos", edit_room_path(@room), class: "btn btn-default" %>
          <% else %>
            <h2 class="mb-5">The owner of the room has not added any photos yet</h2>
          <% end %>
        <% end %>
      </div>
    </div>

    <hr>

    <!-- Reviews -->
    <div class="row my-3">
      <div class="col-sm-12">
        <div id="reviews-header">
          <%= render "reviews/header" %>
        </div>
        <div class="offset-sm-1 col-sm-10 offset-md-2 col-md-8" id="reviews">
          <% if @reviews.blank? %>
            <div class="text-center">
              <h4>There is no review yet</h4>
            </div>
          <% else %>
            <%= render @reviews %>
          <% end %>
        </div>
      </div>
    </div>

    <hr>
    <br>

    <!-- Google Map -->
    <div class="row my-3">
      <div class="col-md-12">
        <div id="map">

          <script>
            // Initialize and add the map
            function initMap() {
              // The location of Uluru
              var uluru = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
              // The map, centered at Uluru
              var map = new google.maps.Map(
                  document.getElementById('map'), {zoom: 14, center: uluru});
              // The marker, positioned at Uluru
              var marker = new google.maps.Marker(
                      {position: uluru, map: map, draggable: true,
                                      animation: google.maps.Animation.DROP,});
            }
          </script>
          <script async defer
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBiE-uKbRKuRyYFA0utax-HXfEdvnblG1U&callback=initMap">
          </script>
        </div>
      </div>
    </div>

    <hr>
    <br>

    <!-- Near by -->
    <h3>Near by</h3>
    <div class="row my-3">

      <% unless @room.nearbys(10).blank? %>
        <% for room in @room.nearbys(10) %>
          <div class="col-lg-3 col-md-4 col-sm-6 col-6 photo-card">
            <div class="photo-container">
              <div class="photo-header">
                <% unless room.photos.blank? %>
                  <%= image_tag room.photos.first.image.url(:medium) %>
                <% else %>
                  <div class="no-img">No image</div>
                <% end %>
              </div>
              <div class="photo-body">
                <div class="photo-title">
                  <%= link_to room.listing_name, room %>
                  <div>(<%= room.distance.round(2) %> miles away)</div>
                </div>
                <p class="lead"><%= room.price %>$ per night</p>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="col-sm-12">
          <h5>there are no nearby places</h5>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>