config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'

get 'signup' => 'users#new', :as => :signup
get 'login' => 'user_sessions#new', :as => :login
post 'login' => 'user_sessions#create'
delete 'logout' => 'user_sessions#destroy', :as => :logout

get 'preload' => 'reservations#preload'
get 'check_conflict' => 'reservations#check_conflict'
get 'your_trips' => 'reservations#your_trips'
get 'your_reservations' => 'reservations#your_reservations'
get 'search' => 'static_pages#search'
get "oauth/callback" => "oauths#callback"
get "oauth/vkontakte" => "oauths#vkontakte"
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
post "oauth/callback" => "oauths#callback"

resources :user_sessions, only: [:new, :create, :destroy]
resources :users
resources :password_resets, only: [:new, :create, :edit, :update]
resources :account_activations, only: [:edit]
resources :photos

resources :rooms do
  resources :reservations, only: [:create]
  resources :reviews, only: [:create, :destroy]
end

resources :conversations, only: [:create, :index] do
  resources :messages, only: [:create, :index] do
    collection { get :events }
  end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(session_params[:email], session_params[:password], session_params[:remember_me])
      if @user.activated?
        flash[:success] = 'Login successful'
        redirect_back_or_to(user_path(@user))
      else
        flash[:danger] = "Yout account is not activated.
                          Please check your email for the activation link"
        redirect_to root_path
      end
    else
      flash.now[:danger] = 'Login failed'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, flash: {success: 'Logged out!'})
  end

  private

    def session_params
      params.require(:user_session).permit(:email, :password, :remember_me)
    end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/user_sessions/new.html.erb
<% provide(:title, "Log in") %>
<h1 class='text-center'>Log in</h1>

<div class="row">
  <div class="col-md-6 offset-md-3 col-lg-4 offset-lg-4">
    <%= form_for(:user_session, url: login_path, method: :post) do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password do %>
          Password
          <%= link_to "(forgot password)", new_password_reset_path %>
        <% end %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <div class="checkbox">
          <%= f.label :remember_me, class: "checkbox inline" do %>
            <%= f.check_box :remember_me %>
            <span>Remember me on this computer</span>
          <% end %>
        </div>
      </div>
      <%= submit_tag "Log in", class: "btn btn-fox offset-md-4" %>
    <% end %>
    <div class="text-center">
      <%= link_to auth_at_provider_path(:provider => :vk) do %>
        <i class="fab fa-vk fa-2x"></i>
      <% end %>
      |
      <%= link_to auth_at_provider_path(:provider => :facebook) do %>
        <i class="fab fa-facebook-square fa-2x"></i>
      <% end %>
    </div>
    <hr class="form_divider">
    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>