config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'

get 'signup' => 'users#new', :as => :signup
get 'login' => 'user_sessions#new', :as => :login
post 'login' => 'user_sessions#create'
delete 'logout' => 'user_sessions#destroy', :as => :logout

get 'preload' => 'reservations#preload'
get 'check_conflict' => 'reservations#check_conflict'
get 'your_trips' => 'reservations#your_trips'
get 'your_reservations' => 'reservations#your_reservations'
get 'search' => 'static_pages#search'
get "oauth/callback" => "oauths#callback"
get "oauth/vkontakte" => "oauths#vkontakte"
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
post "oauth/callback" => "oauths#callback"

resources :user_sessions, only: [:new, :create, :destroy]
resources :users
resources :password_resets, only: [:new, :create, :edit, :update]
resources :account_activations, only: [:edit]
resources :photos

resources :rooms do
  resources :reservations, only: [:create]
  resources :reviews, only: [:create, :destroy]
end

resources :conversations, only: [:create, :index] do
  resources :messages, only: [:create, :index] do
    collection { get :events }
  end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="d-flex flex-row align-items-center pt-2 p-x-4 bg-white border-bottom shadow-sm">
  <div class="container d-flex">
    <%= link_to "BnB", root_path, class: "navbar-brand h1" %>
    <nav>
      <ul class="nav justify-content-end">
        <% unless current_user %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_path, class: 'nav-link text-dark' %></li>
          <li class="nav-item"><%= link_to "Log In", login_path, class: 'nav-link text-dark' %></li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_room_path, class: 'nav-link text-dark' do %>
              <i class="fas fa-home"></i> Become a host
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to conversations_path(current_user), class: 'nav-link text-dark' do %>
              <i class="far fa-envelope" aria-hidden="true"></i> Messages
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag gravatar_url(current_user, size: 35), alt: "Avatar", class: "rounded-circle" %>
              <%= current_user.full_name %>
            </a>
            <div class="dropdown-menu">
              <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Your Listings", rooms_path, class: "dropdown-item" %>
              <%= link_to "Your Reservations", your_reservations_path, class: "dropdown-item" %>
              <%= link_to "Your Trips", your_trips_path, class: "dropdown-item" %>
              <div role="separator" class="dropdown-divider"></div>
              <%= link_to "Log Out", logout_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/rails_default' %>
    <title><%= full_title(yield(:title)) %></title>
    <style><%= yield :stylesheets %></style>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield :home_page %>
    <div class="container mt-3">
      <% unless params[:controller] == 'static_pages' && params[:action] = 'home' %>
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>